apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-system-config
data:
  PROXY_LISTEN_ADDRESS: ":8080"
  PROXY_UPSTREAMS: "http://upstream-api.default.svc.cluster.local:8080"
  PROXY_STATIC_ROOT: "/static"
  PROXY_READ_TIMEOUT: "15s"
  PROXY_WRITE_TIMEOUT: "15s"
  PROXY_IDLE_TIMEOUT: "60s"
  PROXY_SHUTDOWN_TIMEOUT: "20s"
  PROXY_GATEWAY_ENABLED: "true"
  PROXY_POOL: "http://upstream-4g.default.svc.cluster.local:3128|4g|VN-HCM,http://upstream-resi.default.svc.cluster.local:3128|residential|VN-HN"
  PROXY_GATEWAY_HTTP_ADDRESS: ":8888"
  PROXY_GATEWAY_SOCKS_ADDRESS: ":1080"
  PROXY_GATEWAY_ADMIN_ADDRESS: ":9090"
  PROXY_ROTATION: "sticky"
  PROXY_STICKY_TTL: "10m"
  PROXY_HEALTH_INTERVAL: "30s"
  MONGO_URI: "mongodb://mongo.default.svc.cluster.local:27017"
  MONGO_DATABASE: "proxy_gateway"
  MONGO_COLLECTION: "backends"
  MONGO_SYNC_INTERVAL: "10s"
  MONGO_METRICS_FLUSH_INTERVAL: "30s"
